#!/usr/local/bin/bash

dbHost=localhost
dbPassword=jX5L2CGy5ms4ptVJ
userName=transporter
currentDate=$(date +%Y%m%d)
currentTime=$(date +%H%M%S)
backupDir=/backup/mysql/$currentDate
logFile=/var/log/dump-mysql.log

MYSQLDUMP=$(which mysqldump)
TAR=$(which tar)
MYSQL=$(which mysql)

/root/script/keepXdaysV2 /backup/mysql 14 >> $logFile

mkdir -p $backupDir >> $logFile

for i in $(/usr/local/bin/mysql -u $userName -h $dbHost --silent -Ne "show databases;" -p$dbPassword);
do
	#$MYSQLDUMP --create-options --log-error=$logFile --user=$userName -h $dbHost -p$dbPassword $i >> $backupDir/$i-$currentDate.sql
	/usr/local/bin/mysqldump --create-options --log-error=$logFile --user=$userName -h $dbHost -p$dbPassword $i >> $backupDir/$i-$currentDate.sql

        typeset -i dumpStatus=$(echo $?)

        if [ $dumpStatus -eq 0 ];
        then
                echo "$currentDate $currentTime - The dump job for database $i is successful ... " >> $logFile

                $TAR zcf $backupDir/$i-$currentDate.sql.tar.gz $backupDir/$i-$currentDate.sql >> $logFile

                typeset -i tarStatus=$(echo $?)

                if [ $tarStatus -eq 0 ];
                then
                        echo "$currentDate $currentTime - The tar job for database $i is successful ... " >> $logFile

#                        rm -rf $backupDir/$i-$currentDate.sql
                else
                        echo "$currentDate $currentTime - The tar job for database $i has FAILED ... " >> $logFile

                fi
        else
                echo "$currentDate $currentTime - The dump job for database $i has FAILED ... " >> $logFile

        fi
done


